version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/jenkins-x/jx-helpers/v3
    versions:
    - 3.0.100
    - 3.0.101
    - 3.0.104
    - 3.0.105
    - 3.0.106
    - 3.0.72
    - 3.0.73
    - 3.0.74
    - 3.0.77
    - 3.0.84
    - 3.0.86
    - 3.0.88
    - 3.0.89
    - 3.0.90
    - 3.0.91
    - 3.0.93
    - 3.0.94
    - 3.0.96
    - 3.0.97
  - dependency-name: github.com/jenkins-x/jx-api/v4
    versions:
    - 4.0.23
    - 4.0.24
    - 4.0.25
    - 4.0.27
    - 4.0.28
  - dependency-name: github.com/jenkins-x/jx-pipeline
    versions:
    - 0.0.101
    - 0.0.102
    - 0.0.104
    - 0.0.105
    - 0.0.109
    - 0.0.110
    - 0.0.113
    - 0.0.114
    - 0.0.115
    - 0.0.117
    - 0.0.119
    - 0.0.89
    - 0.0.94
    - 0.0.98
    - 0.0.99
  - dependency-name: github.com/jenkins-x/jx-preview
    versions:
    - 0.0.151
    - 0.0.154
    - 0.0.155
    - 0.0.156
    - 0.0.158
    - 0.0.161
    - 0.0.167
    - 0.0.168
    - 0.0.169
    - 0.0.170
    - 0.0.171
  - dependency-name: k8s.io/apimachinery
    versions:
    - 0.20.2
    - 0.20.3
    - 0.20.4
    - 0.20.5
  - dependency-name: github.com/jenkins-x/jx-secret
    versions:
    - 0.0.222
    - 0.0.224
    - 0.0.227
    - 0.0.229
    - 0.0.230
    - 0.1.0
    - 0.1.1
    - 0.1.2
    - 0.1.4
    - 0.1.5
    - 0.1.6
    - 0.1.7
    - 0.1.8
    - 0.1.9
  - dependency-name: github.com/tektoncd/pipeline
    versions:
    - 0.20.1
    - 0.21.0
    - 0.22.0
  - dependency-name: github.com/jenkins-x/jx-logging/v3
    versions:
    - 3.0.3
