apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/005e78cf69b643862344397a635736a51dd1bd89/tasks/git-clone/git-clone.yaml
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: chart
      taskSpec:
        stepTemplate:
          workingDir: /workspace/source
        steps:
        - image: gcr.io/jenkinsxio/builder-go
          name: next-version
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step next-version --use-git-tag-only
        - image: gcr.io/jenkinsxio/builder-go
          name: update-version
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step tag --version $(cat VERSION) --no-apply
        - image: gcr.io/jenkinsxio/builder-go
          name: tag-version
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step tag --version $(cat VERSION)
        - image: gcr.io/jenkinsxio/jx-cli:latest
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx gitops variables
        - image: golang:1.15
          name: release-binary
          resources: {}
          script: |
            #!/bin/bash
            source .jx/variables.sh
            make release
        - image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: changelog
          resources: {}
          script: |
            #!/bin/bash
            source .jx/variables.sh
            jx step changelog --verbose --header-file=hack/changelog-header.md --version=$VERSION --rev=$PULL_BASE_SHA --output-markdown=changelog.md --update-release=false
        - image: gcr.io/jenkinsxio/step-go-releaser:0.0.14
          name: upload-binaries
          resources: {}
          script: |
            #!/bin/bash
            source .jx/variables.sh
            make goreleaser
        - image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: promote-release
          resources: {}
          script: |
            #!/bin/bash
            source .jx/variables.sh
            ./promote.sh
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
